name: Bump Version and Publish to PyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.set-version.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version in pyproject.toml
        id: set-version
        run: |
          current_version=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Current version: $current_version"

          IFS='.' read -r major minor patch <<< "$current_version"
          patch=$((patch + 1))
          if [ $patch -gt 9 ]; then
            patch=0
            minor=$((minor + 1))
            if [ $minor -gt 9 ]; then
              minor=0
              major=$((major + 1))
            fi
          fi

          new_version="$major.$minor.$patch"
          echo "New version: $new_version"
          sed -i "s/version = \"$current_version\"/version = \"$new_version\"/" pyproject.toml

          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "Bump version to ${{ steps.set-version.outputs.new_version }}" || echo "No changes to commit"
          git push

  publish:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
